services:
  client:
    build: 
      context: .
      dockerfile: Dockerfile_dev
    restart: unless-stopped
    expose:
      - 8000
    hostname: mashb1t-traceroute
    container_name: mashb1t-traceroute
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    name: nginx_proxy
    external: true
